name: CI - resolve dependencias (testes)

on:
  push:
    branches:
      - master
jobs:
  pre-fill:
    if: ${{ vars.version  == 0 && vars.subversion == 0 }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: incrementa version
        uses: action-pack/increment@v2
        with:
          name: 'version'
          token: ${{ secrets.REPO_TOKEN }}
          amount: 0

      - name: incrementa subversion
        uses: action-pack/increment@v2
        with:
          name: 'subversion'
          token: ${{ secrets.REPO_TOKEN }}

  build:
    if: ${{ always() }}
    needs: pre-fill
    runs-on: ubuntu-latest
    env:
      tagv: ${{vars.version}}.${{vars.subversion}}

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Criar tag
        id: tag
        env:
          TOKEN: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
        run: |
          git tag rel-$tagv
          git push origin rel-$tagv

      - name: incrementa subversion
        uses: action-pack/increment@v2
        with:
          name: 'subversion'
          token: ${{ secrets.REPO_TOKEN }}

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Compile
        run: mvn clean compile

      - name: Test
        run: mvn test

      - name: Create release package
        env:
          TOKEN: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
        run: |
          mkdir -p release
          cp -r target/* release/
          cd release
          zip -r ../rel-tag.zip .
          cd ..

      - name: Upload release asset
        uses: actions/upload-artifact@v4
        with:
          name: rel-${{vars.version}}.${{vars.subversion}}.zip
          path: rel-tag.zip

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Builds
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/banco:latest
          context: .
          file: .github/workflows/Dockerfile
