name: CI - release candidate
on:
  push:
    tags:
      - 'rc-*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Compile
        run: mvn clean compile

      - name: Super-Linter
        uses: github/super-linter@v6
        env:
            VALIDATE_ALL_CODEBASE: false
            DEFAULT_BRANCH: develop
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: mvn test